version: '3.2'

services:
  nexus-graphql:
    image: node:11.7
    working_dir: /app
    tty: true
    volumes:
      - .:/app
    environment:
      - npm_config_cache=npm-cache
    entrypoint: yarn
    command: ['dev']
